services:
  py_server:
    build:
      context: .
      dockerfile: Dockerfile.py
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DATASET_DIR=/app/model/dataset
      - MODEL_YAML=/app/model/YOLO_files/yolov8-cls.yaml
      - PRETRAINED_MODEL=/app/model/YOLO_files/trained_models/v0.1/best.pt
      - SERVER_URL=http://py_server:8000/predict

  cpp_bot:
    build:
      context: .
      dockerfile: Dockerfile.cpp_bot
    depends_on:
      - py_server
    env_file:
      - ./.env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SERVER_URL=http://py_server:8000/predict