version: '3.8'

services:
  py_server:
    build:
      context: .
      dockerfile: Dockerfile.py
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  cpp_bot:
    build:
      context: .
      dockerfile: Dockerfile.cpp_bot
    depends_on:
      - py_server
    env_file:
      - ./.env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SERVER_URL=http://py_server:8000/predict