[project]
name = "virtual-gardener"
version = "0.2.0"
description = "Service for detecting houseplants illnesses"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.0",
    "torchaudio>=2.6.0",
    "ultralytics>=8.3.107",
]
